INSERT INTO form_gender (form_genderID, form_genderdesc) VALUES (1,'Not Known')
INSERT INTO form_gender (form_genderID, form_genderdesc) VALUES (2,'Male')
INSERT INTO form_gender (form_genderID, form_genderdesc) VALUES (3,'Female')
INSERT INTO form_gender (form_genderID, form_genderdesc) VALUES (9,'Not Applicable')

INSERT INTO form_civilStatus (form_civildesc) VALUES ('Married')
INSERT INTO form_civilStatus (form_civildesc) VALUES ('Widowed')
INSERT INTO form_civilStatus (form_civildesc) VALUES ('Separated')
INSERT INTO form_civilStatus (form_civildesc) VALUES ('Divorced')
INSERT INTO form_civilStatus (form_civildesc) VALUES ('Single')

INSERT INTO form_religion (form_religionDesc) VALUES ('Roman Catholic')
INSERT INTO form_religion (form_religionDesc) VALUES ('Islam')
INSERT INTO form_religion (form_religionDesc) VALUES ('Evangelicals (PCEC)')
INSERT INTO form_religion (form_religionDesc) VALUES ('Iglesia Ni Cristo')
INSERT INTO form_religion (form_religionDesc) VALUES ('Non-Roman Catholic and Protestant (NCCP)')
INSERT INTO form_religion (form_religionDesc) VALUES ('Aglipayan')
INSERT INTO form_religion (form_religionDesc) VALUES ('Seventh-day Adventist')
INSERT INTO form_religion (form_religionDesc) VALUES ('Bible Baptist Church')
INSERT INTO form_religion (form_religionDesc) VALUES ('United Church of Christ in the Philippines')
INSERT INTO form_religion (form_religionDesc) VALUES ('Jehovah''s Witnesses')
INSERT INTO form_religion (form_religionDesc) VALUES ('Church of Christ')
INSERT INTO form_religion (form_religionDesc) VALUES ('Jesus is Lord Church')
INSERT INTO form_religion (form_religionDesc) VALUES ('Tribal Religions')
INSERT INTO form_religion (form_religionDesc) VALUES ('United Pentecostal Church (Philippines) Incorporated')
INSERT INTO form_religion (form_religionDesc) VALUES ('Other Baptist')

INSERT INTO form_clientAssigned(form_clientAssigneddesc) VALUES ('Head Office')

INSERT INTO form_examStatus (form_examStatusdesc) VALUES ('Passed')
INSERT INTO form_examStatus (form_examStatusdesc) VALUES ('Failed')
INSERT INTO form_examStatus (form_examStatusdesc) VALUES ('Incomplete')

INSERT INTO form_educationAttain (form_educationAttaindesc) VALUES ('College Level')
INSERT INTO form_educationAttain (form_educationAttaindesc) VALUES ('College Graduate')
INSERT INTO form_educationAttain (form_educationAttaindesc) VALUES ('High School Graduate')
INSERT INTO form_educationAttain (form_educationAttaindesc) VALUES ('Vocational Graduate')
INSERT INTO form_educationAttain (form_educationAttaindesc) VALUES ('Vocational Level')
INSERT INTO form_educationAttain (form_educationAttaindesc) VALUES ('Post Graduate Level')
INSERT INTO form_educationAttain (form_educationAttaindesc) VALUES ('Post Graduate')

INSERT INTO form_sourcedBy (form_sourcedBydesc) VALUES ('Walk-in')
INSERT INTO form_sourcedBy (form_sourcedBydesc) VALUES ('Job Fair')
INSERT INTO form_sourcedBy (form_sourcedBydesc) VALUES ('Referral')
INSERT INTO form_sourcedBy (form_sourcedBydesc) VALUES ('Online')

INSERT INTO form_applicantStatus (form_applicantStatusdesc) VALUES ('Accepted')
INSERT INTO form_applicantStatus (form_applicantStatusdesc) VALUES ('Pooling')
INSERT INTO form_applicantStatus (form_applicantStatusdesc) VALUES ('Failed')
INSERT INTO form_applicantStatus (form_applicantStatusdesc) VALUES ('Not Qualified')
INSERT INTO form_applicantStatus (form_applicantStatusdesc) VALUES ('Back Out')
INSERT INTO form_applicantStatus (form_applicantStatusdesc) VALUES ('No Show')
INSERT INTO form_applicantStatus (form_applicantStatusdesc) VALUES ('Black Listed')

INSERT INTO form_membershipType (form_membershipTypedesc) VALUES ('Reliever')
INSERT INTO form_membershipType (form_membershipTypedesc) VALUES ('Regular Member')
INSERT INTO form_membershipType (form_membershipTypedesc) VALUES ('Revenue Member')
INSERT INTO form_membershipType (form_membershipTypedesc) VALUES ('Non Revenue Member')

INSERT INTO form_violation (form_violationdesc) VALUES ('Absent without Permission')
INSERT INTO form_violation (form_violationdesc) VALUES ('Not following specific instructions')
INSERT INTO form_violation (form_violationdesc) VALUES ('Abandoning')

INSERT INTO form_offense (form_offensedesc) VALUES ('1st')
INSERT INTO form_offense (form_offensedesc) VALUES ('2nd')
INSERT INTO form_offense (form_offensedesc) VALUES ('3rd')
INSERT INTO form_offense (form_offensedesc) VALUES ('Stay Home')

INSERT INTO form_claimType (form_claimTypedesc) VALUES ('Maternity')
INSERT INTO form_claimType (form_claimTypedesc) VALUES ('Asiapro - Sickness')
INSERT INTO form_claimType (form_claimTypedesc) VALUES ('Asiapro - Accident')
INSERT INTO form_claimType (form_claimTypedesc) VALUES ('SSS - Sickness')
INSERT INTO form_claimType (form_claimTypedesc) VALUES ('Paternity')
INSERT INTO form_claimType (form_claimTypedesc) VALUES ('Solo Parent')
INSERT INTO form_claimType (form_claimTypedesc) VALUES ('HMO')
INSERT INTO form_claimType (form_claimTypedesc) VALUES ('EC - Sickness')
INSERT INTO form_claimType (form_claimTypedesc) VALUES ('VAWC')
INSERT INTO form_claimType (form_claimTypedesc) VALUES ('Magna Carta')
INSERT INTO form_claimType (form_claimTypedesc) VALUES ('Asiapro - MIL')

INSERT INTO form_deathClaim (form_deathClaimdesc) VALUES ('Natural')
INSERT INTO form_deathClaim (form_deathClaimdesc) VALUES ('Accidental')
INSERT INTO form_deathClaim (form_deathClaimdesc) VALUES ('EC')
INSERT INTO form_deathClaim (form_deathClaimdesc) VALUES ('None')

INSERT INTO form_loanType (form_loanTypedesc) VALUES ('EL')
INSERT INTO form_loanType (form_loanTypedesc) VALUES ('MPL')
INSERT INTO form_loanType (form_loanTypedesc) VALUES ('Education Loan')
INSERT INTO form_loanType (form_loanTypedesc) VALUES ('Cellphone Loan')
INSERT INTO form_loanType (form_loanTypedesc) VALUES ('Asiapro Calamity Loan')
INSERT INTO form_loanType (form_loanTypedesc) VALUES ('SSS Salary Loan')
INSERT INTO form_loanType (form_loanTypedesc) VALUES ('SSS Calamity Loan')
INSERT INTO form_loanType (form_loanTypedesc) VALUES ('Pag-ibig Salary Loan')
INSERT INTO form_loanType (form_loanTypedesc) VALUES ('Pag-ibig Calamity Loan')
INSERT INTO form_loanType (form_loanTypedesc) VALUES ('Pag-ibig Housing Loan')
INSERT INTO form_loanType (form_loanTypedesc) VALUES ('Pag-ibig Multi-Purpose Loan')
INSERT INTO form_loanType (form_loanTypedesc) VALUES ('Motorcycle Loan')
INSERT INTO form_loanType (form_loanTypedesc) VALUES ('Appliances Loan')

INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('Chest X-Ray')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('Whole Abdomen Ultrasound')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('Urinalysis')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('ECG')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('Complete Blood Count')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('ESR')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('Fasting Blood Sugar')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('HBA1C')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('Blood Urea Nitrogen')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('Creatinine')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('Blood Uric Acid')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('Cholesterol')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('Triglycerides')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('Lipoprotein Profile')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('Fecalysis')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('SGPT')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('SGOT')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('Alkaline Phosphatase')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('Total Protein with A/G Ratio')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('Bilirubin (B1B2)')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('GGT')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('Na (Sodium)')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('K (Potassium)')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('CL (Chloride)')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('TCa (Total Calcium)')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('CEA (Carcinoembryonic Antigen / Colon)')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('Occult Blood (FIT)')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('Breast Ultrasound')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('PACP (Total ACP & Prostatic ACP)')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('PSA (Prostatic Ca)')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('FT4')
INSERT INTO form_laboratory (form_laboratorydesc) VALUES ('TSH')

INSERT INTO form_addressState (form_addStatedesc) VALUES ('Abra')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Agusan del Norte')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Agusan del Sur')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Aklan')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Albay')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Angeles')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Antique')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Aurora')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Bacolod')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Bago')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Baguio')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Bais')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Basilan')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Basilan City')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Bataan')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Batangas')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Batangas City')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Benguet')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Bohol')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Bukidnon')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Bulacan')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Butuan')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Cabanatuan')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Cadiz')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Cagayan')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Cagayan de Oro')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Calbayog')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Caloocan')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Camarines Norte')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Camarines Sur')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Camiguin')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Canlaon')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Capiz')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Catanduanes')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Cavite')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Cavite City')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Cebu')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Cebu City')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Cotabato')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Dagupan')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Danao')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Dapitan')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Davao City Davao')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Davao del Sur')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Davao Oriental')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Dipolog')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Dumaguete')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Easter Samar')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('General Santos')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Ginoog')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Ifugao')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Iligan')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Ilocos Norte')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Ilocos Sur')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Iloilo')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Iloilo City')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Iriga')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Isabela')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Kalinga-Apayao')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('La Carlota')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('La Union')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Laguna')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Lanao del Norte')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Lanao del Sur')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Laoag')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Lapu-Lapu')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Legazpi')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Leyte')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Lipa')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Lucena')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Maguindanao')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Makati City')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Mandaluyong City')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Mandaue')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Manila')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Marawi')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Marikina City')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Mandaluyong City')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Marinduque')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Masbate')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Mindoro Occidental')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Mindoro Oriental')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Misamis Occidental')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Misamis Oriental')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Mountain Province')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Muntinlupa')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Naga')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Negros Occidental')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Negros Oriental')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('North Cotabato')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Northern Samar')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Nueva Ecija')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Nueva Vizcaya')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Olongapo')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Ormoc')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Oroquieta')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Ozamis')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Pagadian')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Palawan')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Palayan')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Pampanga')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Pangasinan')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Paranaque')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Pasay')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Pasig City')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Puerto Princesa')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Quezon')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Quezon City')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Quirino')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Rizal')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Romblon')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Roxas')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Samar')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('San Carlos (Negros Occidental)')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('San Carlos (Pangasinan)')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('San Jose')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('San Pablo')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Silay')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Siquijor')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Sorsogon')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('South Cotabato')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Southern Leyte')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Sultan Kudarat')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Sulu')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Surigao')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Surigao del Norte')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Surigao del Sur')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Tacloban')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Tagaytay')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Tagbilaran')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Tangub')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Tarlac')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Tawi-tawi')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Toledo')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Trece Marites')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Zambales')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Zamboanga')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Zamboanga del Norte')
INSERT INTO form_addressState (form_addStatedesc) VALUES ('Zamboanga del Sur')

INSERT INTO tbl_role (role_name) VALUES ('Super Admin') 
INSERT INTO tbl_role (role_name) VALUES ('Admin')
INSERT INTO tbl_role (role_name) VALUES ('Employee')

INSERT INTO tbl_access (accs_addUser, accs_actUser, accs_addDocu, accs_edtDocu, accs_delDocu, accs_opnDocu) 
				VALUES (1,1,1,1,1,1)

INSERT INTO tbl_user (role_ID, accs_ID, username, user_pword, user_firstName, user_lastName, user_email, user_contactNo, user_createdDate, user_activate)
				VALUES (1,1,'admin','admin', 'John', 'Doe', 'johndoe@example.com', 09123456789, getdate(), 1)
				
INSERT INTO tbl_documentType (docuType_abbv, docuType_desc) VALUES ('APP','Applicants (Sourcing)')
INSERT INTO tbl_documentType (docuType_abbv, docuType_desc) VALUES ('MEM','Member File 201 (Records, MBS, Sourcing)')
INSERT INTO tbl_documentType (docuType_abbv, docuType_desc) VALUES ('DIR','Disciplinary Records (MBS)')
INSERT INTO tbl_documentType (docuType_abbv, docuType_desc) VALUES ('BNF','Benefits (MBS)')
INSERT INTO tbl_documentType (docuType_abbv, docuType_desc) VALUES ('LOA','Loans (MBS, Finance)')
INSERT INTO tbl_documentType (docuType_abbv, docuType_desc) VALUES ('INV','Invoices (Finance)')
INSERT INTO tbl_documentType (docuType_abbv, docuType_desc) VALUES ('DTR','DTRs Only (Finance)')
INSERT INTO tbl_documentType (docuType_abbv, docuType_desc) VALUES ('RFP','Request for Payments (Finance)')
INSERT INTO tbl_documentType (docuType_abbv, docuType_desc) VALUES ('CWF','Clearances/Waiver Form (Finance, MBS)')
INSERT INTO tbl_documentType (docuType_abbv, docuType_desc) VALUES ('QUI','Quit Claim Form')
INSERT INTO tbl_documentType (docuType_abbv, docuType_desc) VALUES ('LIQ','Liquidations (Finance)')
INSERT INTO tbl_documentType (docuType_abbv, docuType_desc) VALUES ('APE','Annual Physical Exam')